function L=list_toCell(C)
% CONTOURTOCELL convert a contourc list to a cell of arrays
%
%       L=list_toCell(C);
%         L - a cell array of contours
%         C - a list as generated by contourc
%
%       Copyright: Jon Sporring, July 4, 2014

L = cell(list_size(C),1);
i = 1;
ind = 1;
while ind < size(C,2)
    L{i} = C(:,(ind+1):(ind+C(2,ind)));
    ind = ind+C(2,ind)+1;
    i=i+1;
end
end