function I=read_joachim(name,M,N)
%read_joachim reads a file generated by ~joachim/work/BV/Special/Entropy/ent_lin_double etc.

d = round(10000*rand);
eval(sprintf('!cp %s tmp%d',name,d));
eval(sprintf('load tmp%d -ascii',d));
eval(sprintf('!rm tmp%d',d));
eval(sprintf('tmp=tmp%d;',d));

if size(tmp,1)*size(tmp,2) ~= N*M
  error(sprintf('''%s'' is not an (%d,%d) image.',name, M,N));
else
  I = reshape(tmp,M,N);
%  I = zeros(N,M);
%  for i = 1:M
%    I(:,i) = tmp(1+((i-1)*N:i*N-1),1);
%  end
end
